[Dock]
pinnedApps="[{\"id\":\"zen\",\"label\":\"Zen\",\"icon\":\"zen-browser\",\"execName\":\"zen-browser\",\"steamId\":\"\"},{\"id\":\"zeditor\",\"label\":\"Zed\",\"icon\":\"zed\",\"execName\":\"\",\"steamId\":\"\"},{\"id\":\"blender\",\"label\":\"Blender\",\"icon\":\"blender\",\"execName\":\"\",\"steamId\":\"\"},{\"id\":\"org.gnome.Nautilus\",\"label\":\"Files\",\"icon\":\"system-file-manager\",\"execName\":\"nautilus\",\"steamId\":\"\"}]"

[DockConfig]
autoHide=true
iconSize=40
margin=8

[Launcher]
appUsage="{\"steam_app_431730\":3,\"zen\":32,\"bitwig-studio\":1,\"spotify-launcher\":1,\"ghostty\":2,\"zeditor\":1,\"solaar\":4,\"dev.zed.Zed\":17,\"io.github.Foldex.AdwSteamGtk\":3,\"nwg-look\":3,\"browseros\":13,\"qalculate-gtk\":1,\"jconsole-java-jdk\":1,\"lm-studio\":4,\"sdlpop\":1,\"vial-v0.7.5-x86_64\":3,\"hydralauncher\":4,\"org.gnome.Nautilus\":2,\"Alacritty\":1,\"org.manjaro.pamac.manager\":5,\"org.prismlauncher.PrismLauncher\":1,\"heroic\":9,\"org.telegram.desktop\":27,\"io.github.mlm_games.pomodorot\":1,\"nwg-displays\":2,\"hermes\":1,\"cachyos-hello\":1,\"Escape the Backrooms\":1,\"Sniper Elite 5\":18,\"com.obsproject.Studio\":7,\"blender\":9,\"steam\":15,\"Waydroid\":3,\"timeshift-gtk\":1,\"hermes-desktop\":14,\"LinuxToys\":1,\"obsidian\":1,\"thunar\":2,\"io.github.bluemancz.hyprmod\":1}"
hiddenApps=
isGridView=false
wallpaperMediaFilter=all

[System]
idleTimeout=600
isBatterySaverActive=false
lastBrightness=70
nightLightOn=true
preSaverBrightness=100
preSaverProfile=1
suspendTimeout=1200
wasManuallyOverridden=false

[Theme]
isDark=true
