#!/usr/bin/env bash
set -euo pipefail

wallpaper="${1:-}"
dark="${2:-1}"

# QML state stores wallpapers as image:/path, video:/path, or file:///path.
# Iris expects a plain filesystem path, so normalize URI-ish values here.
case "$wallpaper" in
  image:*) wallpaper="${wallpaper#image:}" ;;
  video:*) wallpaper="${wallpaper#video:}" ;;
  file://*) wallpaper="${wallpaper#file://}" ;;
esac

if [[ -z "$wallpaper" || ! -e "$wallpaper" ]]; then
  echo "apply-iris-theme: wallpaper missing: $wallpaper" >&2
  exit 0
fi

if ! command -v iris >/dev/null 2>&1; then
  echo "apply-iris-theme: iris command not found; keeping fallback colors" >&2
  exit 0
fi

cache_dir="$HOME/.cache/meloworld"
mkdir -p "$cache_dir" "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"

json="$(iris "$wallpaper" --dark "$dark" --json-only)"
printf '%s\n' "$json" > "$cache_dir/iris-colors.json.tmp"
mv "$cache_dir/iris-colors.json.tmp" "$cache_dir/iris-colors.json"

IRIS_JSON="$json" python3 - <<'PY'
import json, os, pathlib
c = json.loads(os.environ['IRIS_JSON'])
home = pathlib.Path.home()
cache = home / '.cache' / 'meloworld'
cache.mkdir(parents=True, exist_ok=True)

def color(name, fallback):
    return str(c.get(name) or fallback)

# Iris can legitimately return a strongly saturated dominant color as the
# background (for example olive/green on the current Desert-City gif). That is
# good for accents, but terrible as an app/window surface: Kitty and GTK become
# flat neon blocks. Keep accents dynamic, but clamp the UI surfaces to the
# Meloworld dark earthy base.
raw_bg = color('bg', '#1e1e2e')
raw_fg = color('fg', '#cdd6f4')
raw_surface = color('surface', '#313244')
raw_dim = color('dim', '#6c7086')
if str(c.get('dark', '')).lower() in ('true', '1'):
    bg = '#1d140f'
    surface = '#70462b'
    dim = '#9b6a43'
    fg = '#f3eadb'
else:
    bg = '#f3eadb'
    surface = '#e3cfb4'
    dim = '#8b684d'
    fg = '#21160f'
accent = color('accent', '#89b4fa')
red = color('red', '#f38ba8')
green = color('green', '#a6e3a1')
yellow = color('yellow', '#f9e2af')

# Persist the normalized palette too, so external consumers and QML agree.
normalized = dict(c)
normalized.update({'bg': bg, 'surface': surface, 'dim': dim, 'fg': fg})
(cache / 'iris-colors.json').write_text(json.dumps(normalized, indent=2) + '\n', encoding='utf-8')

kitty = f'''# Generated by meloworld Iris integration. Do not edit by hand.
foreground {fg}
background {bg}
selection_foreground {bg}
selection_background {accent}
cursor {accent}
cursor_text_color {bg}
url_color {accent}
color0 {surface}
color8 {dim}
color1 {red}
color9 {red}
color2 {green}
color10 {green}
color3 {yellow}
color11 {yellow}
color4 {accent}
color12 {accent}
color5 {accent}
color13 {accent}
color6 {accent}
color14 {accent}
color7 {fg}
color15 {fg}
'''
(cache / 'kitty-colors.conf').write_text(kitty, encoding='utf-8')

gtk_common = f'''/* Generated by meloworld Iris integration. Do not edit by hand. */
@define-color accent_color {accent};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {bg};
@define-color destructive_color {red};
@define-color destructive_bg_color {red};
@define-color success_color {green};
@define-color success_bg_color {green};
@define-color warning_color {yellow};
@define-color warning_bg_color {yellow};
@define-color window_bg_color {bg};
@define-color window_fg_color {fg};
@define-color view_bg_color {surface};
@define-color view_fg_color {fg};
@define-color headerbar_bg_color {surface};
@define-color headerbar_fg_color {fg};
@define-color headerbar_backdrop_color {bg};
@define-color popover_bg_color {surface};
@define-color popover_fg_color {fg};
@define-color card_bg_color {surface};
@define-color card_fg_color {fg};
@define-color sidebar_bg_color {surface};
@define-color sidebar_fg_color {fg};
@define-color dialog_bg_color {surface};
@define-color dialog_fg_color {fg};
@define-color shade_color rgba(0,0,0,0.25);
'''

# GTK3: user gtk.css loads after theme, @define-color has natural precedence.
gtk3 = gtk_common

# GTK4: the adw-gtk3-dark theme wraps its color definitions inside
# @media (prefers-color-scheme: dark) {} blocks. Because color-scheme is
# set to prefer-dark, those @media definitions take priority over plain
# @define-color statements in the user gtk.css. To override them, we must
# nest our definitions inside the same @media query so they are evaluated
# *after* the theme's dark-mode overrides.
gtk4 = f'''{gtk_common}
@media (prefers-color-scheme: dark) {{
@define-color window_bg_color {bg};
@define-color window_fg_color {fg};
@define-color view_bg_color {surface};
@define-color view_fg_color {fg};
@define-color headerbar_bg_color {surface};
@define-color headerbar_fg_color {fg};
@define-color headerbar_backdrop_color {bg};
@define-color popover_bg_color {surface};
@define-color popover_fg_color {fg};
@define-color card_bg_color {surface};
@define-color card_fg_color {fg};
@define-color sidebar_bg_color {surface};
@define-color sidebar_fg_color {fg};
@define-color dialog_bg_color {surface};
@define-color dialog_fg_color {fg};
@define-color accent_color {accent};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {bg};
@define-color destructive_color {red};
@define-color destructive_bg_color {red};
@define-color success_color {green};
@define-color success_bg_color {green};
@define-color warning_color {yellow};
@define-color warning_bg_color {yellow};
}}
'''

# Rofi tokens — meloworld-tokens.rasi
rofi_tpl = f'''/* Generated by meloworld Iris — do not edit by hand */
* {{
    bg: {bg};
    bg-hover: {surface};
    bg-select: {surface};

    fg: {fg};
    fg-select: {fg};
    fg-dim: {dim};

    accent: {accent};
    accent-hover: {accent};
    accent-select: {accent};

    red: {red};
    green: {green};
    yellow: {yellow};
    blue: {accent};
    purple: {accent};
    orange: {surface};
}}
'''
rofi_dir = home / '.config/rofi/themes'
rofi_dir.mkdir(parents=True, exist_ok=True)
(rofi_dir / 'meloworld-tokens.rasi').write_text(rofi_tpl, encoding='utf-8')

# Wofi style — replaces hardcoded colors with iris palette
wofi_tpl = f'''/* Wofi Style — Meloworld / iris @{fg}/@{bg}/@{accent} */
/* Generated by meloworld Iris — do not edit by hand */

* {{
    font-family: "Fira Sans Semibold", "Font Awesome 7 Free", "Font Awesome 7 Brands",
                 "Font Awesome 6 Free", "Font Awesome 6 Brands", FontAwesome,
                 "Material Icons", Roboto, Helvetica, Arial, sans-serif;
    font-size: 14px;
}}

window {{
    margin: 0;
    background-color: rgba({int(bg[1:3],16)}, {int(bg[3:5],16)}, {int(bg[5:7],16)}, 0.85);
    border: 1px solid {accent};
    border-radius: 12px;
    box-shadow: 0 4px 24px rgba(0, 0, 0, 0.6), inset 1px 1px 0 rgba({int(fg[1:3],16)}, {int(fg[3:5],16)}, {int(fg[5:7],16)}, 0.08);
}}

#input {{
    margin: 12px 16px;
    padding: 10px 14px;
    background-color: rgba({int(bg[1:3],16)}, {int(bg[3:5],16)}, {int(bg[5:7],16)}, 0.9);
    border: 1px solid {surface};
    border-radius: 8px;
    color: {fg};
    box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.4);
}}

#input:focus {{
    border-color: {accent};
    box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.4), 0 0 0 2px rgba({int(accent[1:3],16)}, {int(accent[3:5],16)}, {int(accent[5:7],16)}, 0.25);
}}

#input * {{
    background-color: transparent;
    color: {fg};
}}

#inner-box {{
    margin: 0 12px 12px 12px;
    padding: 4px;
    background-color: transparent;
}}

#outer-box {{
    margin: 0;
    padding: 0;
    background-color: transparent;
}}

#scroll {{
    margin: 0;
    padding: 4px 0;
}}

#text {{
    margin: 0;
    padding: 0;
    color: {fg};
}}

#entry {{
    margin: 2px 4px;
    padding: 8px 12px;
    border-radius: 8px;
    background-color: transparent;
    color: {fg};
    outline: none;
    transition: all 0.15s ease;
}}

#entry:selected {{
    background: radial-gradient(circle at 50% 250%, rgba({int(accent[1:3],16)}, {int(accent[3:5],16)}, {int(accent[5:7],16)}, 0.2), rgba({int(bg[1:3],16)}, {int(bg[3:5],16)}, {int(bg[5:7],16)}, 0.95)) padding-box,
                linear-gradient({accent}, {accent}) border-box;
    border: 1px solid transparent;
    color: {fg};
    box-shadow: inset 1px 2px 4px rgba({int(fg[1:3],16)}, {int(fg[3:5],16)}, {int(fg[5:7],16)}, 0.1), 0 2px 8px rgba(0, 0, 0, 0.5);
}}

#entry:hover {{
    background-color: rgba({int(surface[1:3],16)}, {int(surface[3:5],16)}, {int(surface[5:7],16)}, 0.5);
}}
'''
wofi_path = home / '.config/wofi/style.css'
wofi_path.write_text(wofi_tpl, encoding='utf-8')

for rel, content in [('.config/gtk-3.0/gtk.css', gtk3), ('.config/gtk-4.0/gtk.css', gtk4)]:
    path = home / rel
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(content, encoding='utf-8')
    tmp.replace(path)
PY

# Let Iris generate any user-configured templates too. Non-fatal: the QML/GTK/Kitty cache above is authoritative.
iris "$wallpaper" --dark "$dark" >/dev/null 2>&1 || true

# Prefer dark/light for GTK/libadwaita according to the same switch.
if command -v gsettings >/dev/null 2>&1; then
  if [[ "$dark" == "1" ]]; then
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark >/dev/null 2>&1 || true
  else
    gsettings set org.gnome.desktop.interface color-scheme prefer-light >/dev/null 2>&1 || true
  fi
fi
